package com.thxbrop.message.theme

import androidx.annotation.ColorInt

open class Theme(
    @ColorInt open val windowBackgroundWhite: Int,
    @ColorInt open val windowBackgroundGray: Int,
    @ColorInt open val actionBarDefault: Int,
    @ColorInt open val actionBarDefaultIcon: Int,
    @ColorInt open val actionBarDefaultTitle: Int,
    @ColorInt open val actionBarDefaultSelector: Int,
    @ColorInt open val actionBarDefaultSubmenuBackground: Int,
    @ColorInt open val actionBarDefaultSubmenuItem: Int,
    @ColorInt open val actionBarDefaultSubmenuItemIcon: Int,
    @ColorInt open val listSelectorSDK21: Int,
    @ColorInt open val divider: Int,
    @ColorInt open val windowBackgroundGrayShadow: Int,
    @ColorInt open val windowBackgroundWhiteGrayText4: Int,
    @ColorInt open val windowBackgroundWhiteBlackText: Int,
    @ColorInt open val windowBackgroundWhiteValueText: Int,
    @ColorInt open val windowBackgroundWhiteBlueHeader: Int,
    @ColorInt open val windowBackgroundWhiteBlueText4: Int,
    @ColorInt open val switchTracker: Int,
    @ColorInt open val switchTrackerChecked: Int,
    @ColorInt open val windowBackgroundWhiteGrayIcon: Int,
    @ColorInt open val player_progressBackground: Int,
    @ColorInt open val player_progress: Int,
    @ColorInt open val featuredStickers_addedIcon: Int,
    @ColorInt open val radioBackground: Int,
    @ColorInt open val radioBackgroundChecked: Int,
    @ColorInt open val windowBackgroundWhiteGrayText2: Int,
    @ColorInt open val chat_inBubble: Int,
    @ColorInt open val chat_inBubbleSelected: Int,
    @ColorInt open val chat_inBubbleShadow: Int,
    @ColorInt open val chat_outBubble: Int,
    @ColorInt open val chat_outBubbleGradient: Int,
    @ColorInt open val chat_outBubbleGradient2: Int,
    @ColorInt open val chat_outBubbleGradient3: Int,
    @ColorInt open val chat_outBubbleSelected: Int,
    @ColorInt open val chat_outBubbleShadow: Int,
    @ColorInt open val chat_messageTextIn: Int,
    @ColorInt open val chat_messageTextOut: Int,
    @ColorInt open val chat_outSentCheck: Int,
    @ColorInt open val chat_outSentCheckSelected: Int,
    @ColorInt open val chat_outSentCheckRead: Int,
)